### ISSUE TITLE
Some questions about parameter transform between functions 

### ISSUE THREAD

**Issue by nebulaoc** [aceld/kis-flow#27]
After reading the example, I have two questions.

1. How to dynamically update related logical functions？I found the FaaS logical function associated actual function (e.g. AvgStuScore, PrintStuAvgScore) is statically compiled.
2. Is there a method to define a parameter transformation relationship.This method will convert the output parameter of the previous function into the input parameter of the next function according to the conversion relationship. The keys of the two arguments may not be the same, and the structure locations may be different.

I am a rookie, maybe my questions are stupid, and I hope to get answers.

**Comment by aceld** [comment]
@nebulaoc 

1.The first question. You understood correctly; functions cannot be dynamically added. They can only be modified through changes in configuration and code followed by recompilation. Currently, KisFlow does not have the capability to dynamically schedule functions via RPC or other distributed mechanisms. This is a feature planned for future iterations of KisFlow to support distributed scheduling of FaaS.

2.For the second question, the input and output of a function are entirely customizable. You can freely configure the input and output parameters. No transformation is needed; you just need to define your output structure within the FaaS. The downstream function can then parse this structure. However, the downstream function needs to be aware of the upstream data structure definition at the business logic level.

**Comment by nebulaoc** [comment]
Thanks for your reply. After you explained my first question, I understood the second question.
