### ISSUE TITLE
suggestion: can support toml file for import or export?

### ISSUE THREAD

**Issue by Cyan1614** [aceld/kis-flow#29]
I think it can support toml format file for import or export configuration.

because a lot of companys use it be configuration files. thank

**Comment by aceld** [comment]
> I think it can support toml format file for import or export configuration.
> 
> because a lot of companys use it be configuration files. thank

@CyanChan 

Thank you for your valuable suggestion. We will consider whether to add support for the TOML format in the future. Of course, if you are able to provide the entire feature, you are welcome to submit a PR and become one of our contributors.
